export const QUESTIONS = [
  "Saya merasa nyaman berada di area ruang terbuka hijau rumah sakit.",
  "Area ruang terbuka hijau memberikan suasana yang tenang bagi saya.",
  "Kondisi ruang terbuka hijau terlihat bersih dan terawat.",
  "Saya merasa aman saat berada di area ruang terbuka hijau.",
  "Ruang terbuka hijau mudah diakses dari lokasi perawatan saya.",
  "Saya merasa lebih rileks setelah mengunjungi ruang terbuka hijau.",
  "Keberadaan ruang terbuka hijau membantu mengurangi tingkat stres saya.",
  "Saya merasa suasana hati menjadi lebih baik setelah berada di ruang terbuka hijau.",
  "Saya merasa lebih optimis selama menjalani masa perawatan.",
  "Saya merasa lebih nyaman menjalani aktivitas sehari-hari setelah mengunjungi ruang terbuka hijau.",
  "Ruang terbuka hijau membantu saya merasa lebih segar secara fisik.",
  "Saya merasa lebih termotivasi untuk melakukan aktivitas ringan setelah mengunjungi ruang terbuka hijau.",
  "Keberadaan ruang terbuka hijau membantu meningkatkan kualitas istirahat saya.",
  "Saya merasa ruang terbuka hijau memberikan manfaat bagi proses pemulihan saya.",
  "Saya merasa keberadaan ruang terbuka hijau penting bagi pasien yang sedang menjalani perawatan.",
];